### ISSUE TITLE
Multiple GPU  

### ISSUE THREAD

**Issue by young-fire** [tanglang96/DataLoaders_DALI#8]
how to use multiple gpu read data?

**Comment by young-fire** [comment]
枚举一个batch   i逐步增大，读取一个batch数据的时间越来越久，这是为啥，是因为硬盘的原因吗

**Comment by tanglang96** [comment]
有可能，可以先用小数据集试试，看下是不是IO的原因

**Comment by xieydd** [comment]
Same question, how to use it in multi-gpus? @tanglang96

**Comment by xieydd** [comment]
@tanglang96 I run it in mutli-gpus , but one problem is , in get_imagenet_dali and get_imagenet_torch the train_loader size is different
```
torch: len(train_loader) is 20019
dali: train_loader._size is 640583
```

**Comment by xieydd** [comment]
And i notice, load is faster,but train is slower with dali, confuse it? @tanglang96

**Comment by tanglang96** [comment]
@xieydd `len(train_loader)` of torch represents the num of batches and `train_loader._size` of dali represents the num of images, you may need little change your codes.
If your gpu is full used without dali, then you don't need to use dali and this should be slower because dali preprocess images with gpu.

**Comment by tanglang96** [comment]
I use multiple gpus with distributed training of [apex](https://github.com/NVIDIA/apex) and its quite stable, you can reference [these codes](https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py) about how to use multiple gpus in detail
